version: "3"

services:
  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    build: ./client
    command: npm run dev
    volumes:
      - ./client:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432

volumes:
  postgres_data:
